
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 18 23:39:49 GMT-03:00 2016
//----------------------------------------------------

package com.ccompiler.analysis;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int SHORT = 42;
  public static final int SIGNED = 45;
  public static final int LEFT_ASSIGN = 24;
  public static final int IDENTIFIER = 2;
  public static final int BOOL = 40;
  public static final int MOD_ASSIGN = 21;
  public static final int OR_OP = 18;
  public static final int GT = 81;
  public static final int ENUMERATION_CONSTANT = 30;
  public static final int SUB_ASSIGN = 23;
  public static final int AND_OP = 17;
  public static final int CONST = 37;
  public static final int REGISTER = 35;
  public static final int DIVOP = 98;
  public static final int ASSIGNMENT = 92;
  public static final int ENUM = 54;
  public static final int IMAGINARY = 51;
  public static final int SIZEOF = 7;
  public static final int MODOP = 97;
  public static final int INC_OP = 9;
  public static final int COMMA = 75;
  public static final int GE_OP = 14;
  public static final int DEC_OP = 10;
  public static final int AND_ASSIGN = 26;
  public static final int LBRK = 87;
  public static final int LT = 80;
  public static final int FUNC_NAME = 6;
  public static final int DOUBLE = 48;
  public static final int STRUCT = 52;
  public static final int LE_OP = 13;
  public static final int XOR_ASSIGN = 27;
  public static final int INLINE = 36;
  public static final int FLOAT = 47;
  public static final int GOTO = 64;
  public static final int F_CONSTANT = 4;
  public static final int RBRK = 88;
  public static final int MINUSOP = 95;
  public static final int RSQRBRK = 79;
  public static final int RIGHT_ASSIGN = 25;
  public static final int GENERIC = 71;
  public static final int ADD_ASSIGN = 22;
  public static final int LONG = 44;
  public static final int QUESTION = 82;
  public static final int LPAR = 85;
  public static final int WHILE = 61;
  public static final int UNION = 53;
  public static final int PLUSOP = 93;
  public static final int LSQRBRK = 78;
  public static final int MUL_ASSIGN = 19;
  public static final int TYPEDEF_NAME = 29;
  public static final int CHAR = 41;
  public static final int PTR_OP = 8;
  public static final int SWITCH = 60;
  public static final int DO = 62;
  public static final int FOR = 63;
  public static final int STAR = 77;
  public static final int VOID = 49;
  public static final int EXTERN = 32;
  public static final int RETURN = 67;
  public static final int SINGLEAND = 89;
  public static final int ELSE = 59;
  public static final int RESTRICT = 38;
  public static final int BREAK = 66;
  public static final int DOT = 76;
  public static final int SOROP = 90;
  public static final int INT = 43;
  public static final int BINNEG = 96;
  public static final int STRING_LITERAL = 5;
  public static final int LOGNEGATION = 94;
  public static final int SEMICOLON = 83;
  public static final int EOF = 0;
  public static final int RPAR = 86;
  public static final int DEFAULT = 57;
  public static final int XOROP = 91;
  public static final int error = 1;
  public static final int RIGHT_OP = 12;
  public static final int OR_ASSIGN = 28;
  public static final int ALIGNOF = 69;
  public static final int CONTINUE = 65;
  public static final int IF = 58;
  public static final int UNSIGNED = 46;
  public static final int DIV_ASSIGN = 20;
  public static final int COLON = 84;
  public static final int ATOMIC = 70;
  public static final int STATIC_ASSERT = 73;
  public static final int NORETURN = 72;
  public static final int VOLATILE = 39;
  public static final int NE_OP = 16;
  public static final int CASE = 56;
  public static final int EQ_OP = 15;
  public static final int I_CONSTANT = 3;
  public static final int THREAD_LOCAL = 74;
  public static final int COMPLEX = 50;
  public static final int ELLIPSIS = 55;
  public static final int STATIC = 33;
  public static final int TYPEDEF = 31;
  public static final int AUTO = 34;
  public static final int LEFT_OP = 11;
  public static final int ALIGNAS = 68;
}

